AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ImportToRDS:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.6
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: devopsteststore
        S3Key: 73157bf7a45bf06fabefd92f43e4d350
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::455166022519:role/S3toRDSLambda
