AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ImportToRDS:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Code: src/lambda.zip
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::455166022519:role/S3toRDSLambda